chore: use escape double quotation marks for windows
tidb-community-bots/ti-community-bot pull request #140
Opened 2020-11-25 11:23 UTC by Mini256

2020-11-25 11:25 UTC, Mini256 commented
PTAL~ @hi-rustin

2020-11-25 11:25 UTC, hi-rustin commented
Could you please add the windows ci?

2020-11-25 11:31 UTC, Mini256 commented
> Could you please add the windows ci?

ok, I will try to add it tomorrow.

2020-11-26 02:47 UTC, hi-rustin commented
The CI broken.

2020-11-26 03:25 UTC, hi-rustin commented
/hold

2020-11-26 09:03 UTC, hi-rustin commented
@Mini256  Please revert your last commit. I will try to fix the CI issue.

2020-11-26 09:22 UTC, hi-rustin requested changes

2020-11-26 09:22 UTC, hi-rustin commented on .github/workflows/test.yml
> -        os: [ ubuntu-latest, macos-latest ] # FIXME: prettier can not working on windows.
Please revert the FIXME.

2020-11-26 09:22 UTC, Mini256 commented on .github/workflows/test.yml
> -        os: [ ubuntu-latest, macos-latest ] # FIXME: prettier can not working on windows.
ok

2020-11-26 09:27 UTC, hi-rustin approved these changes
Good Job!

2020-11-26 09:27 UTC, hi-rustin commented
/merge

2020-11-26 09:31 UTC, hi-rustin commented
/hold cancel

Windows CI still have issue, maybe fix it in the future.

2020-11-26 09:31 UTC, merged